### PR TITLE
fix: stringstream concatenation

### PR DESCRIPTION
**Pull request by hdetering**
When trying to compile on Linux (Lubuntu 16.04 with g++ 5.4.0) with the following command:

```
g++ -std=c++11 *.cpp -o scite
```

the following error occurred:

```
output.cpp:187:9: error: cannot bind ‘std::ostream {aka std::basic_ostream<char>}’ lvalue to ‘std::basic_ostream<char>&&’
[...]
```

Traced it down to the concatenation of `stringstream`s which only worked when converting the right hand stringstream to string using `str()`.

### CODE REVIEW

**Comment by jahnka** [comment]
Thanks for tracing down the problem.
